# -*- coding: utf-8 -*-
"""latest of GVHMR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3uTheiBZxdM7bN8INmJte479sbqeSW0

## Installation

Check [INSTALL.md](https://github.com/IsshikiHugh/GVHMR/blob/main/docs/INSTALL.md) if you want to install GVHMR on your own machine.

> Tips: you can fold the section and run the whole installation section at once.
"""

# Controlling notebook is connected to NVIDIA drivers with CUDA. If this doesn't load check that GPU is selected as hardware accelerator under Edit -> Notebook settings.
# Google may shut down the GPU if usage has surpassed the allocation

!nvidia-smi

"""### Environment Prepration ~ 15 min

Check [INSTALL.md#Environment](https://github.com/IsshikiHugh/GVHMR/blob/main/docs/INSTALL.md#environment) for further information.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/
import torch
print(torch.__version__)
!python --version

!pip install https://github.com/MiroPsota/torch_packages_builder/releases/download/pytorch3d-0.7.8/pytorch3d-0.7.8+pt2.6.0cu124-cp311-cp311-linux_x86_64.whl
!pip install yacs

from pathlib import Path

proj_root = str(Path('GVHMR').absolute())

# Commented out IPython magic to ensure Python compatibility.
import os

# Clone the repo.
!git clone https://github.com/zju3dv/GVHMR.git

# Install GVHMR. (If Colab asks you to restart, just click cancel and rerun the block.)
# %cd {proj_root}

# replace the requirements.txt with this:

'''
# PyTorch
--extra-index-url https://download.pytorch.org/whl/cu121
#torch==2.3.0+cu121
#torchvision==0.18.0+cu121
timm  # For HMR2.0a feature extraction

# Lightning + Hydra
lightning
hydra-core
hydra-zen
hydra_colorlog
rich

# Common utilities
numpy
jupyter
matplotlib
ipdb
setuptools>=68.0
black
tensorboardX
opencv-python
ffmpeg-python
scikit-image
termcolor
einops
imageio
av  # imageio[pyav], improved performance over imageio[ffmpeg]
joblib

# Diffusion
# diffusers[torch]==0.19.3
# transformers==4.31.0

# 3D-Vision
#pytorch3d @ https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu121_pyt230/pytorch3d-0.7.6-cp310-cp310-linux_x86_64.whl
trimesh
chumpy
smplx
# open3d==0.17.0
wis3d
pycolmap

# 2D-Pose
ultralytics==8.2.42  # YOLO
cython_bbox
lapx

'''

# Commented out IPython magic to ensure Python compatibility.
proj_root = '/content/GVHMR'
# %cd {proj_root}
# %pip install -r requirements.txt
# %pip install -e .

# # Install DPVO.
# %cd third-party/DPVO

# !wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
# !unzip -o eigen-3.4.0.zip -d thirdparty && rm -rf eigen-3.4.0.zip

# %pip install torch-scatter -f "https://data.pyg.org/whl/torch-2.3.0+cu121.html"
# %pip install numba pypose

# if 'cuda_home' not in locals():
#   cuda_home = '/usr/local/cuda-12'
#   if not Path(cuda_home).exists():
#     raise FileNotFoundError('CUDA_HOME for cuda 12.x not found!')

#   os.environ['CUDA_HOME'] = cuda_home
#   os.environ['PATH'] = os.environ['PATH'] + f':{cuda_home}/bin'

# %pip install -e .
# %cd {proj_root}

!pip install ffmpeg-python

"""### Data Prepration ~ 1 min

Check [INSTALL.md#Inputs&Outputs](https://github.com/IsshikiHugh/GVHMR/blob/main/docs/INSTALL.md#inputs--outputs) for further information.
"""

# Commented out IPython magic to ensure Python compatibility.


# %cd {proj_root}


!mkdir inputs
!mkdir outputs

!apt install -y -qq aria2
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/camenduru/SMPLer-X/resolve/main/SMPL_NEUTRAL.pkl -d inputs/checkpoints/body_models/smpl -o SMPL_NEUTRAL.pkl
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/camenduru/SMPLer-X/resolve/main/SMPLX_NEUTRAL.npz -d inputs/checkpoints/body_models/smplx -o SMPLX_NEUTRAL.npz
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/camenduru/GVHMR/resolve/main/dpvo/dpvo.pth -d inputs/checkpoints/dpvo -o dpvo.pth
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/camenduru/GVHMR/resolve/main/gvhmr/gvhmr_siga24_release.ckpt -d inputs/checkpoints/gvhmr -o gvhmr_siga24_release.ckpt
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/camenduru/GVHMR/resolve/main/hmr2/epoch%3D10-step%3D25000.ckpt -d inputs/checkpoints/hmr2 -o epoch=10-step=25000.ckpt
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/camenduru/GVHMR/resolve/main/vitpose/vitpose-h-multi-coco.pth -d inputs/checkpoints/vitpose -o vitpose-h-multi-coco.pth
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/camenduru/GVHMR/resolve/main/yolo/yolov8x.pt -d inputs/checkpoints/yolo -o yolov8x.pt

"""## Run Demo

Use `-s` to skip visual odometry <b><u>if you know the camera is static</u></b>, otherwise the camera will be estimated by DPVO.

We also provide a script demo_folder.py to inference a entire folder.


```shell
python tools/demo/demo.py --video=docs/example_video/tennis.mp4 -s
python tools/demo/demo_folder.py -f inputs/demo/folder_in -d outputs/demo/folder_out -s

```
"""

import io
import base64
from IPython.display import HTML
from hmr4d.utils.video_io_utils import get_video_lwh

def display_video(fn):
    L, W, H = get_video_lwh(fn)
    scale = min(W, 1080) / W
    W, H = int(W * scale), int(H * scale)
    video_encoded = base64.b64encode(io.open(fn, 'rb').read())
    return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                        <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                        </video>'''.format(W, H, video_encoded.decode('ascii')))

"""### Demo Tennis"""

# Run demo.
old = 'ckpt = torch.load(file, map_location="cpu")'
new = 'ckpt = torch.load(file, map_location="cpu", weights_only=False)'

!sed -i 's/{old}/{new}/g' /usr/local/lib/python3.11/dist-packages/ultralytics/nn/tasks.py

!pip install chump -U
!pip install pyinvoke -U
!pip install numpy==1.23.5

!pip install chumpy
!sed -i 's/getargspec/getfullargspec/g' /usr/local/lib/python3.11/dist-packages/chumpy/ch.py

# Commented out IPython magic to ensure Python compatibility.



video_fn = f'/content/GVHMR/thatch_factory.mp4'
!cd /content/GVHMR
# %cd /content/GVHMR
!python /content/GVHMR/tools/demo/demo.py --video={video_fn} -s

# Commented out IPython magic to ensure Python compatibility.
# Install needed packages
!pip install matplotlib pytorch3d

# Go into correct folder
# %cd /content/GVHMR/tools/demo

# Then run it like this:
!python demo.py \
  --video='/content/GVHMR/thatch_factory.mp4' \
  --output_root='/content/GVHMR/outputs' \
  --static_cam \
  --verbose

import numpy as np

# Load the .npz file
npz_file = np.load('/content/GVHMR/outputs/demo/thatch_factory/hmr4d_results.npz')
print(npz_file.files)

# Access arrays
global_orient = npz_file['global_orient']  # (3, 3)
body_pose = npz_file['body_pose']          # (3, 63)
betas = npz_file['betas']                  # (3, 10)
transl = npz_file['transl']                 # (3, 3)
K_fullimg = npz_file['K_fullimg']           # (3, 3, 3)

# Example: print shapes
print(global_orient.shape)
print(body_pose.shape)
print(betas.shape)
print(transl.shape)
print(K_fullimg.shape)

""".npz → .json"""

import numpy as np
import json

# Load your .npz file
npz_path = '/content/GVHMR/outputs/demo/thatch_factory/hmr4d_results.npz'
npz_data = np.load(npz_path)

# Convert all arrays to lists
data_dict = {}
for key in npz_data.files:
    data_dict[key] = npz_data[key].tolist()  # convert numpy array -> python list

# Save as JSON
json_path = npz_path.replace('.npz', '.json')
with open(json_path, 'w') as f:
    json.dump(data_dict, f)

print(f"Saved {json_path}")

"""Load npz → SMPL decode → save joints/vertices to JSON"""

import torch
import numpy as np
import json
from smplx import SMPL

# 1. Load .npz
npz_path = '/content/GVHMR/outputs/demo/thatch_factory/hmr4d_results.npz'
data = np.load(npz_path)

global_orient = torch.tensor(data['global_orient'])  # (frames, 3)
body_pose = torch.tensor(data['body_pose'])          # (frames, 63)
betas = torch.tensor(data['betas'])                  # (frames, 10)
transl = torch.tensor(data['transl'])                 # (frames, 3)

# 2. Load SMPL model
smpl = SMPL(
    model_path='/content/GVHMR/inputs/checkpoints/body_models/smpl',
    gender='neutral',
    batch_size=global_orient.shape[0]
)

# 3. Fix body_pose dimension
frames = body_pose.shape[0]
body_pose_padded = torch.cat(
    [body_pose, torch.zeros((frames, 6))],
    dim=1
)

# 4. Forward pass
output = smpl(
    global_orient=global_orient,
    body_pose=body_pose_padded,
    betas=betas,
    transl=transl
)

# 5. Only get joints
joints = output.joints  # (frames, 45, 3)

# 6. Convert to list
joints_list = joints.cpu().numpy().tolist()

# 7. Create dictionary
output_dict = {
    'joints_3d': joints_list
}

# 8. Save to JSON
json_path = npz_path.replace('.npz', '_joints_only.json')
with open(json_path, 'w') as f:
    json.dump(output_dict, f)

print(f"Saved joints ONLY to {json_path}")

"""See figure"""

import json
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# 1. Load the joints JSON
json_path = '/content/GVHMR/outputs/demo/thatch_factory/hmr4d_results.json'
with open(json_path, 'r') as f:
    data = json.load(f)

joints_3d = np.array(data['joints_3d'])  # (frames, 54, 3)

# 2. Select only important 16 joints
important_joints_idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 15, 16, 17, 18]
filtered_joints_3d = joints_3d[:, important_joints_idx, :]  # (frames, 16, 3)

# 3. Define correct SMPL skeleton connections
smplx_connections = [
    (0, 1), (1, 4), (4, 7),    # Pelvis → Left hip → Left knee → Left ankle
    (0, 2), (2, 5), (5, 8),    # Pelvis → Right hip → Right knee → Right ankle
    (0, 3), (3, 6), (6, 9),    # Pelvis → Spine1 → Spine2 → Neck
    (9, 10), (10, 12), (12, 14), # Neck → Left shoulder → Left elbow → Left wrist
    (9, 11), (11, 13), (13, 15)  # Neck → Right shoulder → Right elbow → Right wrist
]

# 4. Plot one frame
frame_idx = 0  # you can change this to 1, 2, etc.
joints = filtered_joints_3d[frame_idx]

fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111, projection='3d')

# Plot joints
ax.scatter(joints[:, 0], joints[:, 1], joints[:, 2], c='r', s=30)

# Plot bones
for (i, j) in smplx_connections:
    x = [joints[i, 0], joints[j, 0]]
    y = [joints[i, 1], joints[j, 1]]
    z = [joints[i, 2], joints[j, 2]]
    ax.plot(x, y, z, c='b', linewidth=2)

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title(f'Stick Figure - Frame {frame_idx}')
ax.set_box_aspect([1,1,1])

# Flip Y axis if needed (optional)
# ax.invert_yaxis()

plt.show()

"""Overlay Stick Figure on Video"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load joints and camera intrinsics
json_path = '/content/GVHMR/outputs/demo/thatch_factory/hmr4d_results_joints_only.json'
npz_path = '/content/GVHMR/outputs/demo/thatch_factory/hmr4d_results.npz'
video_path = '/content/GVHMR/thatch_factory.mp4'

# Load joints
with open(json_path, 'r') as f:
    data = json.load(f)
joints_3d = np.array(data['joints_3d'])  # (frames, 54, 3)

# Load camera intrinsics
npz_data = np.load(npz_path)
K_fullimg = npz_data['K_fullimg']  # (frames, 3, 3)

# Video reader
cap = cv2.VideoCapture(video_path)

# Frame index to show
frame_idx = 0

# Go to frame
cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
ret, frame = cap.read()
if not ret:
    raise Exception(f"Cannot read frame {frame_idx}")

frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

# Important joints only
important_joints_idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 15, 16, 17, 18]
joints = joints_3d[frame_idx, important_joints_idx, :]  # (16, 3)
K = K_fullimg[frame_idx]

# Project 3D joints to 2D
joints_hom = np.concatenate([joints, np.ones((joints.shape[0], 1))], axis=1)  # (16, 4)
proj_2d = (K @ joints_hom[:, :3].T).T  # (16, 3)
proj_2d = proj_2d[:, :2] / proj_2d[:, 2:]

# Stick figure connections
smplx_connections = [
    (0, 1), (1, 4), (4, 7),
    (0, 2), (2, 5), (5, 8),
    (0, 3), (3, 6), (6, 9),
    (9, 10), (10, 12), (12, 14),
    (9, 11), (11, 13), (13, 15)
]

# Plot
fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(frame_rgb)
ax.scatter(proj_2d[:, 0], proj_2d[:, 1], c='r', s=30)

for (i, j) in smplx_connections:
    x = [proj_2d[i, 0], proj_2d[j, 0]]
    y = [proj_2d[i, 1], proj_2d[j, 1]]
    ax.plot(x, y, c='b', linewidth=2)

ax.set_title(f'Frame {frame_idx} Stick Figure on Video')
ax.axis('off')
plt.show()

cap.release()

"""3D SMPLX Viewer in Colab"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib notebook

import numpy as np
import torch
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from smplx import SMPLX  # you must have smplx installed

# Load GVHMR .npz result
data = np.load('/content/GVHMR/outputs/demo/thatch_factory/hmr4d_results.npz')

frame_idx = 0  # which frame you want

# Extract pose params
global_orient = torch.tensor(data['global_orient'][frame_idx]).unsqueeze(0)  # (1, 3)
body_pose = torch.tensor(data['body_pose'][frame_idx]).unsqueeze(0)          # (1, 63)
betas = torch.tensor(data['betas'][frame_idx]).unsqueeze(0)                  # (1, 10)
transl = torch.tensor(data['transl'][frame_idx]).unsqueeze(0)                # (1, 3)

# Load SMPLX model
model_path = '/content/models/smplx'  # you must download smplx models here
model = SMPLX(model_path=model_path, gender='neutral', use_pca=False)

# Forward model
output = model(global_orient=global_orient, body_pose=body_pose, betas=betas, transl=transl)

vertices = output.vertices[0].detach().cpu().numpy()
joints = output.joints[0].detach().cpu().numpy()

# Plot
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')

# Vertices
ax.scatter(vertices[:, 0], vertices[:, 1], vertices[:, 2], s=0.1, c='gray', alpha=0.6, label='Vertices')

# Joints
ax.scatter(joints[:, 0], joints[:, 1], joints[:, 2], s=20, c='red', label='Joints')

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.view_init(elev=20, azim=60)
ax.legend()
plt.tight_layout()
plt.show()

# - raw model output json/parameters?
#   - could be dense/sparse:
#       it may be the output is the whole figure of the person, in which case
#       we can probably find specific indices on that figure to define poses.
#       But otherwise, we'll get a simple json to define on.
# - run over each person in the scene
#   - they seem to use yolo to find people, and they may just select the first/
#     most confident output. Otherwise, we can always do our own automatic cropping.

from IPython.display import Video

def display_video(path):
    return Video(path, embed=True)

# Now call it
display_video('/content/GVHMR/outputs/demo/Untitled-1/Untitled-1_3_incam_global_horiz.mp4')

"""### Custom Demo

In order to run your own video, you need to follow instructions below:

0. Run the code block below to initialize `demo_google_drive_video()`.
1. Upload your video on Google drive and set accessbility as "Anyone with link (Viewer)".
2. Copy the link and extract the ID. The link should follow this pattern: `https://drive.google.com/file/d/<Google Drive ID>/view?usp=sharing`.
3. Call `demo_google_drive_video()` with the URL, and pass `True` if the camera is static.

"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {proj_root}
!mkdir -p inputs/demo

def demo_google_drive_video(url:str, static_camera:bool):
    ''' URL should be like https://drive.google.com/file/d/xxxxxxxx/view?usp=drive_link '''

    print(f'[1/3] 📥 Downloading video...')
    gdid = url.split('/')[5]
    video_name = f'custom_{gdid}'
    download_url = f'\'https://drive.google.com/uc?id={gdid}&export=download&confirm=t\''
    !gdown {download_url} -O inputs/demo/{video_name}.mp4

    print(f'[2/3] 💃 Start running GVHMR...')
    flag = '-s' if static_camera else ''
    !python {proj_root}/tools/demo/demo.py --video=inputs/demo/{video_name}.mp4 {flag}

    print(f'[3/3] 📺 Displaying result...')
    return display_video(f'outputs/demo/{video_name}/{video_name}_3_incam_global_horiz.mp4')

demo_google_drive_video(url='https://drive.google.com/file/d/1KkTsoAuj9yq5JCJ-qg4_MnNBn56wR47F/view?usp=drive_link', static_camera=True)

# Try it yourself!
demo_google_drive_video(...)